[package]
name = "crypto-pals"
version = "0.1.0"
authors = ["Jesse Huard <jhuard@ualberta.ca>"]

[dependencies]
rustc-serialize = "0.3.14"

[lib]
name = "crypto"
path = "src/lib.rs"

[[bin]]
name = "set1c1"
path = "src/bin/set1/c1.rs"
